# Generated by Django 4.2.20 on 2025-03-19 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataverse', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataCareer',
            new_name='DataRole',
        ),
    ]
