# Generated by Django 4.2.20 on 2025-03-19 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataverse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datarole',
            name='yolo',
            field=models.CharField(default='NUll', max_length=100, unique=True),
        ),
    ]
