# Generated by Django 4.2.20 on 2025-03-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataverse', '0002_rename_datacareer_datarole'),
    ]

    operations = [
        migrations.AddField(
            model_name='datarole',
            name='description',
            field=models.TextField(default='NODESC'),
        ),
    ]
