# Generated by Django 4.2.20 on 2025-03-19 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataverse', '0002_datarole_yolo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datarole',
            name='yolo',
            field=models.CharField(default='NUll', max_length=100),
        ),
    ]
