# Generated by Django 4.2.20 on 2025-07-10 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataverse', '0002_alter_article_insight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='insight',
        ),
    ]
