# Generated by Django 4.2.20 on 2025-03-19 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataverse', '0003_alter_datarole_yolo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datarole',
            name='yolo',
        ),
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
