# Generated by Django 4.2.20 on 2025-03-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataverse', '0004_remove_datarole_yolo_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='datarole',
            name='category_role',
            field=models.TextField(default='NODESC'),
        ),
    ]
