# Generated by Django 4.2.20 on 2025-07-10 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataverse', '0005_datarole_category_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='insight',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, null=True,
            blank=True, related_name='articles', to='dataverse.datainsight'),
        ),
    ]
