# Generated by Django 4.2.20 on 2025-07-10 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataverse', '0008_insight_article_insight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='insight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='dataverse.insight'),
        ),
    ]
